Created Homepage, along with nav bar, you can navigate to different p…
too-many-cookies/front-end pull request #4
Opened 2022-09-12 22:07 UTC by emc3424

…ages, and look at a brief hard coded table of recent activity. There is an issue with using bootstrap charts

2022-09-12 23:40 UTC, ethanrusz requested changes
I've requested some changes, mostly to do with code styling and one for some unused vars. Besides that, it looks good and runs as expected in the container.

2022-09-12 23:40 UTC, emrusz commented on src/App.js
> +    //     <Button variant="orange">Test</Button> */}
Please remove template comments if they are no longer needed. (The variables defined in them are setting off eslint.)

![image](https://user-images.githubusercontent.com/35783974/189776083-be7d1923-dc2b-4b2a-8a9c-44b3330455b1.png)

2022-09-12 23:40 UTC, ethanrusz commented on src/components/Navbar.js
> +export default Navbar
Please add a trailing newline.

2022-09-12 23:40 UTC, ethanrusz commented on src/pages/Activitylog.js
> +export default ActivityLog;
Please add a trailing newline.

2022-09-12 23:40 UTC, ethanrusz commented on src/pages/Classes.js
> +export default Classes;
Please add a trailing newline.

2022-09-12 23:40 UTC, ethanrusz commented on src/styles/navbar.css
> +}
Please add a trailing newline.

2022-09-22 20:48 UTC, JordanMRabideau approved these changes

2022-09-23 14:08 UTC, ethanrusz approved these changes

2022-09-23 14:14 UTC, merged